project:
  type: book

book:
  title: Essentials For Python Programming
  author: \textcolor{blue}{\textbf{STATS\_SOLUTIONS}}@ryannthegeek
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - 1_Numbers_and_operators.ipynb
    - 2_Output.ipynb
    - 3_Variables.ipynb
    - 4_Literals.ipynb
    - 5_Functions.ipynb
    - 6_Strings.ipynb
    - 7_Set.ipynb
    - 8_Lists.ipynb
    - 9_Decision_making_statements.ipynb
    - 10_Loops.ipynb
    - 11_Tuple.ipynb
    - 12_Dictionary.ipynb
    - 13_Classes_and_objects.ipynb
    - 14_Dates_and_times.ipynb
    - 15_Files_handling.ipynb
    - 16_Importing_modules.ipynb
    - 17_NumPy.ipynb
    - 18_Pandas.ipynb



format:  
  pdf:
    documentclass: report
    classoption: [12pt, a4paper, oneside, openright]
    toc: true
    toc-title: Contents
    toc-depth: 4
    toccolor: blue
    number-sections: true
    number-depth: 3
    lof: true
    lot: true
    fig-format: png
    fig-pos: H
    urlcolor: purple
    colorlinks: true
    linkcolor: blue
    filecolor: magenta
    citecolor: blue
    link-citations: true
    listings: true
    include-in-header: 
      - /home/chege/Documents/Data-Science/latex-files/listsetP.tex
      - /home/chege/Documents/Data-Science/latex-files/contactdets.tex
    latex-auto-install: true
    output-file: Essentials For Python Programming

jupyter: python3
execute:
  warning: false
  error: false
  cache: false
  freeze: auto



