project:
  type: book

book:
  title: Data Analysis with Python Book
  author: \textcolor{blue}{\textbf{STATS\_SOLUTIONS}}@ryannthegeek
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - 01_data_analysis_with_python.ipynb





format:  
  pdf:
    documentclass: report
    classoption: [12pt, a4paper, oneside, openright]
    toc: true
    toc-title: Contents
    toc-depth: 4
    toccolor: blue
    number-sections: true
    number-depth: 3
    lof: true
    lot: true
    fig-format: png
    fig-pos: H
    urlcolor: purple
    colorlinks: true
    linkcolor: blue
    filecolor: magenta
    citecolor: blue
    link-citations: true
    listings: true
    include-in-header: 
      - /home/chege/Documents/Data-Science/latex-files/listsetP.tex
      - /home/chege/Documents/Data-Science/latex-files/contactdets.tex
    latex-auto-install: true
    output-file: Data Analysis with Python Book

jupyter: python3
execute:
  warning: false
  error: false
  cache: false
  freeze: auto



